export const LOGIN_SUCCESS='LOGIN_SUCCESS';
export const LOGOUT="LOGOUT";
export const GET_ACCESS_TOKEN_SUCCESS='GET_ACCESS_TOKEN_SUCCESS';
export const GET_VIDEO_LIST='GET_VIDEO_LIST';
export const GET_VIDEO="GET_VIDEO";

