export const AUTHORIZE_SUCCESS='AUTHORIZE_SUCCESS';
export const GET_ACCESS_TOKEN_SUCCESS='GET_ACCESS_TOKEN_SUCCESS';
export const GET_VIDEO_LIST='GET_VIDEO_LIST';
export const LOGIN_STATE='LOGIN_STATE';
